apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    podname: secondpodlb
spec:
  containers:
   - name: firstcontainer
     image: coolgourav147/nginx-custom
---
apiVersion: v1
kind: Service
metadata:
  name: my-internal-service
spec: 
  selector: 
    app: secondpodlb
  ports:  
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP