apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    label1: harshal
    label2: gaurav
    label3: saurav
spec:
  containers:
   - name: maincontainer
     image: coolgourav147/nginx-custom
     env:
      - name: myname
        value: Gaurav
      - name: city
        value: Jaipur
  initContainers:
    - name: initcontainer
      image: coolgourav147/nginx-custom
      args: ["sleep", "30" ]